### ISSUE TITLE
Installs wrong csv2notion-neo package on x86 Macs

### ISSUE THREAD

**Issue by bumper314** [TheAcharya/homebrew-tap#1]
Running `brew install TheAcharya/homebrew-tap/csv2notion-neo` installs the unusable ARM version of the package instead of the x86 version on Intel Macs.

**Comment by unfixa1** [comment]
It may be due to some settings or package configuration issues of Homebrew. Homebrew is not compatible with Mac and has many bugs. It is recommended that you use tools such as [servbay](servbay.com) to check the development environment and try redeploying.

**Comment by IAmVigneswaran** [comment]
@bumper314 We have drop support for Intel Macs some time back.
