### ISSUE TITLE
`/usr/local/bin` is not in the default macOS path

### ISSUE THREAD

**Issue by lgarron** [TheAcharya/homebrew-tap#2]
The `markers-extractor` formula installs a binary to `/usr/local/bin`, which is not in the default macOS path. Wanted to try it, but was left scratching my head. 😅

Ideally, I think the formula should specify a binary and allow Homebrew to handle the install location, but `/usr/bin` would be a better hardcoded path if not.

**Comment by IAmVigneswaran** [comment]
@lgarron I am not an expert in Homebrew.

I believe `/usr/bin` is where binaries supplied by the OS be installed and `/usr/local/bin` is where user supplied binaries would be installed.

I would prefer to have a hardcoded path of `/usr/local/bin`.
